server:
  port: 8081
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 200
        max-idle: 200
        max-wait: -1
        min-idle: 0
    timeout: 300
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xiaoyuanmai?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    password: root
  jpa:
    hibernate:

      ddl-auto: update
#      database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

