server:
  port: 8081
spring:
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xiaoyuanmai?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    password: root
  jpa:
    hibernate:

      ddl-auto: update
#      database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

